services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: taskbuddy
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: taskbuddy
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
